FROM golang:alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
WORKDIR $GOPATH/src/github.com/wicaker/user

# Run tests
CMD CGO_ENABLED=0 go test ./...